title: Spectral Blog
author: Mihaly Balogh
email: baloghmnihaly@hotmail.de
description: > # this means to ignore newlines until "baseurl:"
  This is going to be my personal professional blog about IT, team culture, remote working and digital nomadship.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
